---
apiVersion: v1
kind: Namespace
metadata:
  name: ping-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: ping-test
data:
  bootstrap.servers: "tansu.tansu.svc.cluster.local:9092"
  default.topic.partitions: "1"
  default.topic.replication.factor: "1"
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: kafka-broker
  namespace: ping-test
  annotations:
    eventing.knative.dev/broker.class: Kafka
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: ping-test
