---
apiVersion: v1
kind: Namespace
metadata:
  name: ping-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-display
  namespace: ping-test
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: event-display
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
---
kind: Service
apiVersion: v1
metadata:
  name: event-display
  namespace: ping-test
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
