apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: test-ping-source
  namespace: ping-test
spec:
  schedule: "*/10 * * * * *"
  contentType: "application/json"
  data: '{"ok":true}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker
      namespace: ping-test
